# Generated by Django 5.1.4 on 2025-01-03 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('school_name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('director', 'School Director'), ('proprietor', 'Proprietor'), ('head_teacher', 'Head Teacher')], max_length=50)),
                ('school_address', models.CharField(max_length=255)),
                ('landmark', models.CharField(max_length=255)),
                ('school_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('primary_secondary', 'Primary & Secondary')], max_length=50)),
                ('laptop', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('computer_lab', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('finance_tool', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('results_tool', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('cbt_exam', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.lga')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.state')),
            ],
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='Home.state'),
        ),
    ]
