# Generated by Django 5.1.4 on 2025-01-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolregistration',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='Phone Number'),
        ),
    ]
